Adding WSO2 input output mappers
wso2-extensions/siddhi-map-wso2event pull request #1
Opened 2017-06-13 13:01 UTC by ramindu90

2017-06-13 13:15 UTC, suhothayan commented on components/input-mapper/pom.xml
> +                            org.wso2.siddhi.extension.input.mapper.wso2event.*
the package name should be org.wso2.extension.siddhi.map.wso2event

2017-06-13 13:16 UTC, suhothayan commented on components/input-mapper/src/main/java/org/wso2/siddhi/extension/input/mapper/wso2event/WSO2SourceMapper.java
> +                                "Used to provide the incoming event's wso2event stream id",
give an example

2017-06-13 13:18 UTC, suhothayan requested changes

2017-06-13 13:18 UTC, suhothayan commented on components/output-mapper/src/main/java/org/wso2/siddhi/extension/output/mapper/wso2event/WSO2SinkMapper.java
> +                        description =
give an example value

2017-06-13 13:23 UTC, ramindu90 commented on components/input-mapper/pom.xml
> +                            org.wso2.siddhi.extension.input.mapper.wso2event.*
@suhothayan , since this is the wso2event **input** mapper, shouldnt the package name contain "input" as well?

2017-06-13 13:34 UTC, ramindu90 commented on components/input-mapper/src/main/java/org/wso2/siddhi/extension/input/mapper/wso2event/WSO2SourceMapper.java
> +                                "Used to provide the incoming event's wso2event stream id",
Added the forgotten parameter arbitrary.map.
The examples were already in the latter part

2017-06-13 13:35 UTC, ramindu90 commented on components/output-mapper/src/main/java/org/wso2/siddhi/extension/output/mapper/wso2event/WSO2SinkMapper.java
> +                        description =
Added the forgotten parameter arbitrary.map.
The examples were already in the latter part of the extension description

2017-06-14 02:32 UTC, suhothayan commented on components/input-mapper/pom.xml
> +                            org.wso2.siddhi.extension.input.mapper.wso2event.*
its source mapper right.
if you need source then it should come after wso2event name.
e.g. org.wso2.extension.siddhi.map.wso2event.source

2017-06-14 02:33 UTC, suhothayan commented on components/input-mapper/src/main/java/org/wso2/siddhi/extension/input/mapper/wso2event/WSO2SourceMapper.java
> +                                "Used to provide the incoming event's wso2event stream id",
I want the format to be in the description <name>:<version> and version needs to be in x.x.x format.

2017-06-14 04:30 UTC, ramindu90 commented on components/input-mapper/pom.xml
> +                            org.wso2.siddhi.extension.input.mapper.wso2event.*
added the module names with the source and sink names

2017-06-14 04:30 UTC, ramindu90 commented on components/input-mapper/src/main/java/org/wso2/siddhi/extension/input/mapper/wso2event/WSO2SourceMapper.java
> +                                "Used to provide the incoming event's wso2event stream id",
added examples for wso2event.stream.id and arbitrary.map parameters

2017-06-14 11:16 UTC, suhothayan approved these changes

2017-06-14 11:16 UTC, merged